name: KRX Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 다운로드
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 라이브러리 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python 실행
        run: python script.py
