name: Telegram Bot

on:
  schedule:
    - cron: "30 06 * * *"
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 다운로드
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 라이브러리 설치
        run: |
          pip install requests
          pip install finance-datareader

      - name: Python 실행
        run: python script.py
